FROM mageai/mageai:latest

ARG USER_CODE_PATH=/home/src/${PROJECT_NAME}

# Note: this overwrites the requirements.txt file in your new project on first run. 
# You can delete this line for the second run :) 
COPY requirements.mage.txt ${USER_CODE_PATH}/requirements.mage.txt 

RUN pip3 install -r ${USER_CODE_PATH}/requirements.mage.txt

RUN python -m spacy download en_core_web_sm