{
 "title": "Glimmerfox",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Cost, $",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(openai_cost) AS total_cost\r\nFROM queries\r\nWHERE \r\n  timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND openai_cost > 0"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  total_tokens\r\nFROM queries\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "+1/-1",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  SUM(CASE WHEN feedback = 1 THEN 1 ELSE 0 END) as thumbs_up, \r\n  SUM(CASE WHEN feedback = 0 THEN 1 ELSE 0 END) as thumbs_down \r\nFROM feedback \r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Relevancy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  relevance,\r\n  COUNT(*) as count\r\nFROM queries\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY relevance"
    }
   ]
  },
  {
   "title": "OpenAI cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  openai_cost\r\nFROM queries\r\nWHERE openai_cost > 0\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  response_time\r\nFROM queries\r\nORDER BY timestamp"
    }
   ]
  }
 ]
}